# Generated by Django 6.0.3 on 2026-03-04 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='allergen_info',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='calories_per_100g',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('unit', 'Unidad'), ('g', 'Gramos'), ('kg', 'Kilogramos'), ('ml', 'Mililitros'), ('l', 'Litros'), ('tbsp', 'Cucharada'), ('tsp', 'Cucharadita'), ('cup', 'Taza')], default='unit', max_length=12),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Facil'), ('medium', 'Media'), ('hard', 'Dificil')], default='medium', max_length=12),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tips',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklymenu',
            name='friday_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus_friday', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='weeklymenu',
            name='monday_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus_monday', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='weeklymenu',
            name='name',
            field=models.CharField(default='Menu semanal', max_length=120),
        ),
        migrations.AddField(
            model_name='weeklymenu',
            name='saturday_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus_saturday', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='weeklymenu',
            name='sunday_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus_sunday', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='weeklymenu',
            name='thursday_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus_thursday', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='weeklymenu',
            name='tuesday_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus_tuesday', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='weeklymenu',
            name='wednesday_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus_wednesday', to='recipes.recipe'),
        ),
    ]
