# Generated by Django 6.0.3 on 2026-03-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient_allergen_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['nombre']},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='allergen_info',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='calories_per_100g',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='alergenos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='apto_celiacos',
            field=models.CharField(blank=True, choices=[('si', 'si'), ('no', 'no'), ('puede_contener_gluten', 'puede contener gluten')], max_length=30),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='apto_halal',
            field=models.CharField(blank=True, choices=[('si', 'si'), ('no', 'no')], max_length=3),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='apto_keto',
            field=models.CharField(blank=True, choices=[('si', 'si'), ('no', 'no')], max_length=3),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='apto_kosher',
            field=models.CharField(blank=True, choices=[('si', 'si'), ('no', 'no')], max_length=3),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='apto_vegano',
            field=models.CharField(blank=True, choices=[('si', 'si'), ('no', 'no')], max_length=3),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='apto_vegetariano',
            field=models.CharField(blank=True, choices=[('si', 'si'), ('no', 'no')], max_length=3),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='azucares_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='beneficios_nutricionales',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='calorias_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbohidratos_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='categoria',
            field=models.CharField(blank=True, choices=[('verdura', 'verdura'), ('fruta', 'fruta'), ('carne', 'carne'), ('pescado', 'pescado'), ('marisco', 'marisco'), ('cereal', 'cereal'), ('legumbre', 'legumbre'), ('lacteo', 'lacteo'), ('huevo', 'huevo'), ('especia', 'especia'), ('hierba_aromatica', 'hierba aromatica'), ('fruto_seco', 'fruto seco'), ('semilla', 'semilla'), ('grasa_aceite', 'grasa / aceite'), ('azucar_endulzante', 'azucar / endulzante'), ('bebida', 'bebida'), ('hongo', 'hongo')], max_length=40),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='combinaciones_habituales',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='contraindicaciones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='duracion_conservacion',
            field=models.CharField(blank=True, choices=[('horas', 'horas'), ('dias', 'dias'), ('semanas', 'semanas'), ('meses', 'meses'), ('anos', 'anos')], max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='etiquetas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fibra_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='forma_conservacion',
            field=models.CharField(blank=True, choices=[('refrigerado', 'refrigerado'), ('congelado', 'congelado'), ('seco', 'seco'), ('en_salmuera', 'en salmuera'), ('en_aceite', 'en aceite'), ('al_vacio', 'al vacio')], max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fuente_informacion',
            field=models.CharField(blank=True, choices=[('base_nutricional', 'base de datos nutricional'), ('literatura_cientifica', 'literatura cientifica'), ('wikipedia', 'wikipedia'), ('etiqueta_producto', 'etiqueta de producto'), ('usuario_editor', 'usuario / editor')], max_length=30),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='grasas_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='grasas_saturadas_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='imagen_archivo',
            field=models.FileField(blank=True, null=True, upload_to='ingredients/'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='imagen_modo',
            field=models.CharField(choices=[('ruta', 'ruta de imagen'), ('url', 'url'), ('archivo', 'archivo subido')], default='ruta', max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='imagen_ruta',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='indice_glucemico',
            field=models.CharField(blank=True, choices=[('bajo', 'bajo (0-55)'), ('medio', 'medio (56-69)'), ('alto', 'alto (70+)')], max_length=10),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='lugar_compra',
            field=models.CharField(blank=True, choices=[('supermercado', 'supermercado'), ('mercado', 'mercado'), ('pescaderia', 'pescaderia'), ('carniceria', 'carniceria'), ('fruteria', 'fruteria'), ('herbolario', 'herbolario'), ('tienda_online', 'tienda online')], max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='metodos_cocinado',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='minerales',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nombre',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nombre_cientifico',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='origen_geografico',
            field=models.CharField(blank=True, choices=[('pais', 'pais'), ('region', 'region'), ('denominacion_origen', 'denominacion de origen'), ('continente', 'continente')], max_length=30),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='parte_utilizada',
            field=models.CharField(blank=True, choices=[('raiz', 'raiz'), ('hoja', 'hoja'), ('tallo', 'tallo'), ('fruto', 'fruto'), ('semilla', 'semilla'), ('flor', 'flor'), ('bulbo', 'bulbo'), ('tuberculo', 'tuberculo'), ('musculo', 'musculo'), ('organo', 'organo')], max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='precio_aproximado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='proteinas_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recetas_relacionadas',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sabor_predominante',
            field=models.CharField(blank=True, choices=[('dulce', 'dulce'), ('salado', 'salado'), ('acido', 'acido'), ('amargo', 'amargo'), ('umami', 'umami'), ('picante', 'picante')], max_length=15),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sal_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sodio_100g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('pescado_azul', 'pescado azul'), ('pescado_blanco', 'pescado blanco'), ('carne_roja', 'carne roja'), ('carne_blanca', 'carne blanca'), ('legumbre_seca', 'legumbre seca'), ('legumbre_fresca', 'legumbre fresca'), ('cereal_integral', 'cereal integral'), ('cereal_refinado', 'cereal refinado'), ('lacteo_fermentado', 'lacteo fermentado'), ('lacteo_fresco', 'lacteo fresco'), ('fruto_seco_tostado', 'fruto seco tostado'), ('fruto_seco_crudo', 'fruto seco crudo')], max_length=40),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='temperatura_conservacion',
            field=models.CharField(blank=True, choices=[('ambiente', 'ambiente'), ('4c', '4C refrigeracion'), ('-18c', '-18C congelacion')], max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='temporada',
            field=models.CharField(blank=True, choices=[('primavera', 'primavera'), ('verano', 'verano'), ('otono', 'otono'), ('invierno', 'invierno'), ('todo_el_ano', 'todo el ano')], max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='textura',
            field=models.CharField(blank=True, choices=[('crujiente', 'crujiente'), ('blando', 'blando'), ('cremoso', 'cremoso'), ('fibroso', 'fibroso'), ('gelatinoso', 'gelatinoso'), ('jugoso', 'jugoso'), ('seco', 'seco')], max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='tipo_ingrediente',
            field=models.CharField(blank=True, choices=[('principal', 'principal'), ('secundario', 'secundario'), ('condimento', 'condimento'), ('espesante', 'espesante'), ('aromatizante', 'aromatizante'), ('guarnicion', 'guarnicion')], max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='tipo_origen',
            field=models.CharField(blank=True, choices=[('vegetal', 'vegetal'), ('animal', 'animal'), ('mineral', 'mineral'), ('fungico', 'fungico'), ('sintetico', 'sintetico')], max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unidad_compra',
            field=models.CharField(blank=True, choices=[('gramo', 'gramo'), ('kilogramo', 'kilogramo'), ('mililitro', 'mililitro'), ('litro', 'litro'), ('unidad', 'unidad'), ('pieza', 'pieza'), ('cucharada', 'cucharada'), ('cucharadita', 'cucharadita')], max_length=20),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='vitaminas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
