# Generated by Django 6.0.3 on 2026-03-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdc_id', models.BigIntegerField(db_index=True, unique=True)),
                ('alimento', models.CharField(db_index=True, max_length=300)),
                ('nutrientes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['alimento'],
            },
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.RemoveField(
            model_name='weeklymenu',
            name='tuesday_recipe',
        ),
        migrations.RemoveField(
            model_name='weeklymenu',
            name='thursday_recipe',
        ),
        migrations.RemoveField(
            model_name='weeklymenu',
            name='wednesday_recipe',
        ),
        migrations.RemoveField(
            model_name='weeklymenu',
            name='friday_recipe',
        ),
        migrations.RemoveField(
            model_name='weeklymenu',
            name='sunday_recipe',
        ),
        migrations.RemoveField(
            model_name='weeklymenu',
            name='monday_recipe',
        ),
        migrations.RemoveField(
            model_name='weeklymenu',
            name='saturday_recipe',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='WeeklyMenu',
        ),
    ]
