# Generated by Django 6.0.3 on 2026-03-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_csvingredient_delete_ingredient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalInfoIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('scientific_name', models.CharField(blank=True, default='', max_length=300)),
                ('edible_portion', models.FloatField(blank=True, null=True)),
                ('energy_total', models.FloatField(blank=True, null=True)),
                ('protein_total', models.FloatField(blank=True, null=True)),
                ('nutrients', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='CsvIngredient',
        ),
    ]
