# Generated by Django 6.0.3 on 2026-03-06 11:36

import django.db.models.deletion
from django.db import migrations, models
import unicodedata


def _normalize(value: str) -> str:
    text = (value or "").strip().lower()
    text = "".join(
        ch for ch in unicodedata.normalize("NFKD", text) if not unicodedata.combining(ch)
    )
    return " ".join(text.split())


def populate_normalized_names_and_aliases(apps, schema_editor):
    Ingredient = apps.get_model("recipes", "NutritionalInfoIngredient")
    Alias = apps.get_model("recipes", "IngredientSearchAlias")

    for ingredient in Ingredient.objects.all().only("id", "name"):
        ingredient.normalized_name = _normalize(ingredient.name)
        ingredient.save(update_fields=["normalized_name"])

    seed_aliases = [
        ("pimiento verde", "green bell pepper"),
        ("pimiento rojo", "red bell pepper"),
        ("curcuma", "turmeric"),
        ("cúrcuma", "turmeric"),
        ("calabacin", "zucchini"),
        ("calabacín", "zucchini"),
        ("cebolla morada", "red onion"),
        ("judias verdes", "green beans"),
        ("judías verdes", "green beans"),
    ]

    for alias_es, usda_query_en in seed_aliases:
        Alias.objects.update_or_create(
            alias_normalized=_normalize(alias_es),
            defaults={
                "alias_es": alias_es,
                "usda_query_en": usda_query_en,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_nutritionalinfoingredient_delete_csvingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionalinfoingredient',
            name='fdc_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='nutritionalinfoingredient',
            name='normalized_name',
            field=models.CharField(db_index=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='nutritionalinfoingredient',
            name='source',
            field=models.CharField(choices=[('csv_import', 'CSV import'), ('usda_api', 'USDA API')], db_index=True, default='csv_import', max_length=20),
        ),
        migrations.AddField(
            model_name='nutritionalinfoingredient',
            name='source_name_en',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='nutritionalinfoingredient',
            name='source_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='IngredientSearchAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_es', models.CharField(max_length=150, unique=True)),
                ('alias_normalized', models.CharField(db_index=True, max_length=150, unique=True)),
                ('usda_query_en', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_aliases', to='recipes.nutritionalinfoingredient')),
            ],
            options={
                'ordering': ['alias_es'],
            },
        ),
        migrations.RunPython(populate_normalized_names_and_aliases, migrations.RunPython.noop),
    ]
