# Generated by Django 6.0.3 on 2026-03-06 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_nutritionalinfoingredient_fdc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsearchalias',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_aliases', to='recipes.nutritionalinfoingredient'),
        ),
    ]
