# Generated by Django 6.0.3 on 2026-03-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_ingredientsearchalias_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulinaryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('normalized_name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('source', models.CharField(choices=[('seed', 'Seed'), ('manual', 'Manual')], db_index=True, default='seed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
